#+TITLE: System Testing, Implementation and Maintenance


* Software Testing
Software testing is evaluation of the software against requirements gathered from users and system specifications. Testing is conducted at the phase level in software development life cycle or at module level in program code. Software testing comprises of *Validation* and *Verification*.
** Software Validation
Validation is process of examining whether or not the software satisfies the user requirements. It is carries out at the end of the SDLC. If the software matches requirements for which it was made, it is validated.
+ Validation ensures the product under development is as per the user requirements.
+ Validation answers the question - "Are we developing the product which attempts all the user needs from this software?"
+ Validation emphasizes on *user requirements*.
** Software Verification
Varification is the process of confirming if the software is meeting the business requirements, and is developed adhering the proper specifications and methodologies.
+ Verification ensures the product being developed is according to design specifications.
+ Verification answers the question - "Are we developing this product firmly following all design specifications?"
+ Verifications concentrate on the design and system specifications.
** Targets of the test are -
+ *Errors*
  These are actual coding mistakes made by developers.
  In addition, there is a difference in output of software and desired output, is considered as an error.
+ *Fault*
  When error exists fault occurs. A fault, also known as a bug, is a result of an error which can cause system to fail.
+ *Failure*
  Failure is said to be the inability of the system to perform the desired task. Failure occurs when fault exists in the system.

* Manual VS Automated Testing
** Manual
This testing is performed without taking help of automated testing tools. The software tester prepares test cases for different sections and level of the code, executes the test and reports the result to the manager.


Manual testing is time and resource consuming. The tester need to confirm whether or not right test cases are used. Major portion of testing involves manula testing.
** Automated
This testing is a testing procedure done with aid of automated testing tools. The limitations with manual testing can be overcome using automated test tools. There are software and hardware tools which helps tester in conducting load testing, stress testing, regression testing.

* Testing Approaches
** Functionality Testing
** Implementation Testing
