#+TITLE: Computer Networks
#+DESCRIPTION: Notes For Computer Networks
#+AUTHOR: Mitansh Panchal(looph0le)

* Introduction
** Clients and Servers
A client is somebody who buys goods for
companiers and other organisation may also be clients.

Example:
 + A person who wants to access a website.

A server is a computer or system that provides resources, data, services, programs, to other computers, known as clients over a network.

** How a server works
When a client requiers data or functionality from a server, it sends requests over then network.
The servers recieves this request and responds with the appropriate information.

This is the request and response model of client server networking.

It is also known as call and response model.

A server often performs neumerous additional tasks as part of a single request and response, including varifying the identity of the requester, ensuring that the client has permission to access the data or resources requested, and properly formating or determining the requierd response in an expected way.
** Types of Servers
*** File Server
A File server store and destribute files. Multiple clients or users may share files stored on the server.
In addition, central storing files often easier to backup or fault tolerans solutions and integrity for files on every device in an organisation.

File server hardware can be designed to maximize read and write speeds to improve performance.
*** Print Server
A print server or printing server is a type of server that connects printers to client computers over a network.
It accepts print jobs from the computers and sends the job to the appropriate printers, queuing the job locally
to accommodate the fact that work may arrive more quickly than the printer can actually handle.

*** Application Server
*** Web Server
*** Database Server
*** Proxy Server
*** Virtual Server
*** Mail Server


If we want to transfer data or information between the computers there are two ways.
1. Without using network
2. With the help of networks
Just imagine that there are two computers which do not have any connection, still we want to transfer
data then we have to use extra resources like Pen Drive, CD or DVD and compy it to other computer.
This process is time consuming and requires more resources and money.
With the help of network. We can transfer data or information all over the world from one system to another system.
This process is easy, fast, secure and reliable.
** Definition of Network:
*** Computer Networks
Computer network is defined as two or more computers are connected in such a way that they can
share their data, information as well as their resources.
Computer Network is the interconnected collection of autonoumous computer and peripheral devices.
The links connecting the devices are called /communication channels/.
The concept of connecting computers for sharing resources or data are called /Networking/.
Two computer are said to be interconnected if they are able to exchange /data/ and /information/.
*** Characteristics of Network
**** Resource Sharing:
It means all the computers within the network are able to share their resources which include
all the programs, data, and devices available to anyone on the network without considering the
physical location of the resource and user.
**** High reliability:
Network provides high reliability by having alternative sources of supply.
**** Saving money:
Mostly in networking, one computer work as server and other as client means only server computer
require connection with resource and all other client can easily access it. So, it requires less
hardware, hence saving a ton of money.
**** Powerful communication medium:
One a network, when one person make any change to a document. The other person can see the change
immediatly instead of waiting several days.
**** Scalability:
Network is able to increase system performace as the work grows, just by upgrading the hardware.
**** Low cost:
Using networks, we are able to talk with any person at any part of the world with a low cost
compare to telephone system.
**** Time saving:
E-mail services require less time compare to postal services.
**** Flexibility of equipment location:
We can change location anytime.
**** Improved performace:
We can improve performace by adding new efficient network hardware.
*** Networks are used by people because:
**** Access to remote information
**** Person to person communication
**** Interactive Entertaiment
*** Advantages/Needs of Computer Network:
**** Efficient management of resources
**** Faster Data sharing
**** Keeping information reliable and up to date
**** High reliability
**** Efficient communication
** Network Criteria:
Effective and efficient network must be able to meet following criteria.
*** Performace
Performace of a network is measured by two times.
**** Transit time
Time requied for a message to travel from one device to anoter.
**** Response time
Elapsed time between inquiry and response.
*** Reliablity
Network reliability is measured by
**** Frequency of failure
All networks fail occasionally.
A network that fails often however is a little value.
**** Recovery time of a network after a failure
A network that recovers quickly is more useful that one that does not.
**** Catastrophe events
Network must be protected from the catastrophe events like fire, earthquake, tsunami, etc.
**** Security
Network security include protecting data from unauthorized access and viruses
***** Unautorized access
Sensitive data must be protected from unauthorized access.
***** Viruses
Network is accessible from many access points and can be susceptible to computer viruses.
A virus is introduced to code that damages the system. A good network is protected to computer viruses.
** Network Applications:
*** Financial Services
Credit history searches, foreign exchange, investment services and electronic money transfer, etc.
*** Marketing and sales
Marketing people use them for collecting, exchange and analyze data relating to customer.
Sales applications include teleshopping, online reservation services, railway, airline, etc.
*** Electronic messaging
E-mail services are possible using networks.
*** Manufacturing
Computer networks are used in manufacturing processes.
*** Directory service
It allows list of files to be stored in particular location and search operation for the file.
*** Information Services
World wide web site offers the information services.
*** Cable television
This also uses computer networking concept
*** Teleconferencing
It allows conference to occure witout the particular being in same place.
It includes text, audio and video conferencing.
*** Electronic data exchange
It allows business information to be transferred witout using paper.
** Network Hardware
Network hardware is defined as a collection of physical network components to establish a network area.
Hardware components are.
- Transmission media which include Guided media like twisted pair, coaxial cable and fiber optic cable unguided media like radio wave, microwave and infrared.
- Servers
- Workstation / clients / Nodes / Terminals
- Connectors
- NIC (Network Interface Card)
- Modem
- Networking and internetworking devices like repeaters, Hub, Bridge, Switch, Router, Gateway.
** Defination of Protocol
Protocol is a set of rules that manages all aspects of data communication. It represents an agreement between the communication devices. Without a protocol, two devices may be connected but not communicating.
A protocol defines what is communicated, how it is communicated and when it is communicated.
*** Key Element of Protocol are
**** Syntax:
Syntax refers to the formate of the data or structure of data syntax tells us the order in which data are presented.
**** Sementics:
Sementics refers to the meaning of each section of bits, how particular pattern to be represented is and what action is to be taken based on that presentation.
**** Timing:
Timing refers to the characteristics
- When data should be sent
- How fast they can sent
*** Examples of protcols
- SMTP (Simple Mail Transfer Protocol)
- POP (Post Office Protocol)
- TCP (Transmission Control Protocol)
- UDP (User Datagram Protocol)
- IP (Internet Protocol)
** Standard Organization
A standard provides model for development that makes it possible for products from different manufactures can work together.
Standard are essential for creating and maintaining an open and competative market for manufacturers.
Standard provide guidlines to manufacturer vendors, government agencies and other service providers.
Data communication standards falls into two categories.
*** De facto (By fact):
Standards that have been approved by an organized body but have been adopted as standard are De Facto standard.
De facto standards are mostly established by manifacturers.
*** De Jure (By law):
Standards that have been approved by an offically recognized body are De Jure standards.
Standards are developed by corporation among standard creation committee, forums and government regulatory agencies.

*** Following are the communcation standards
**** ISO : International Standards Organizations
ISO is the worlds largest developer and publisher of international standards.
Founded in 1946, ISO is an international organization composed of national standards bodies from over 157 countries, one member per country, based on Geneva, Switzerland, that coordinates the systems.
**** CCITT : Consultative Committee for International Telegraphy and Telephony
This committee was devoted to the research and established of standard for telecommunications.
In march 1, 1993 the name of this committee was changed to ITU-T(International Telecommunication Union-Telecommunication Standards Sector).
**** ANSI : American National Standards Institute
The American National Standards Institute or ANSI is a private non-profit organization that oversees the development of voluntary consensus standards for product, services, processes, systems, and personnel in the United States.
The organization also coordinates U.S. standards with international standards so that the American products can be used worldwide.
**** IEEE : Institute of Electrical and Electronics Engineers
Is an international non-profit, professional organization for the advancement of technology related to electricity.
The IEEE is incorporeated in the State of New York, United States.
The major interests of the AIEE were wire communcation(telegraph and telephony) and light and power systems.
**** ITU : International Telecommunication Union
Is the oldest international organization, establish to standardize and regulate international radio and telecommunications.
ITU was founded in 1865 and became a United Nations Agency in 1947.
**** ISOC : Internet Society
Is an international, non-profit organization founded during 1992 to provide direction in internet related standards, education, and policy.
It states that its mission is "to assure the open development, evolution and use of the internet of the benefit of all people throughout the world"
**** IETF : Internet Engineering Task Force
IETF develops and promotes internet standards, coorperating closely with the W3C(World Wide Web Consortium)
and ISO/IEC(International Electrotechnical Commission) standards bodies and dealing in particular with standards of the TCP/IP and internet protocol suit.
**** EIA : Electronic Industries Association
Is a trade organisation of electronics manufacturers in the United States.
* Basic Concepts
** Line Configuration
Line configuration defines the attachment of communcation devices to a link.
A link is a physical communication pathway that transfers data from one device to another device.
For communicating to occure, two devices must be connected in some way to the same link at the same time.
Types of line configuration.
*** Point-to-point:
Two and only t  wo devices are connected by a dedicated link. Dedicated means that link carries traffic between connected devices only.
In this configuration, entire capacity of the channel is reserved for transmission between two devices.
*** Multipoint:
A multipoint configuration is one in which more than two specific devices share a single link.
In this configuration. the capacity of the channel is shared either spatially or temporarily.
**** Spactially Shared link configuration:
If several devices can use the link simultaneouly(at same time) is called spatially shared link configuration.
**** Time Shared Line Configuration:
It means some fixed slots are given to the users are called time-shared line configuration.
** Topology
Topology which refers to the way interconnection path between many users or nodes are arranged. Or, Actual layout of network transmission media.
*** Physical Topology:
A network refers to the configuration of cables, computers and other peripherals.
*** Logical Topology:
Which is a method used to pass information between workstations.
*** Types of topologies:
**** Bus topology
Also known as linear bus topology. It consists of several computers attached to a long common cable act as backbone to link all the devices in the network.
In bus topology, data on the network is send to all the computers on the network.
The data travels from one end of the cable to another end.
However only the computer that has the address matching the address in the single accpets the data.
only one computer at a time can send message.

**** Star topology
**** Ring topology
**** Mesh topology
**** Tree topology
*** Categories of network
Network classify according to their geographical size.
Network referring to three primary categories.
**** LAN(Local Area Network)
LAN is a group of computers and network communication devices interconnected within the geographical limited area. Such as office, Buildings.
LAN tends to use only one type of transmission medium was cabling.
***** Characteristics of LAN
***** Advantages of LAN
**** MAN
