#+TITLE: Data Types, Variables and Arrays
#+HTML_HEAD: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.css">


* Java is a strongly Typed Language
It is important to state at the outset that java is a strongly typed language. Indeed, part of java's safety and robustness comes from this fact. Let's see what this means. First, every variable has a type, every expression has a type, and every type is strictly defined.
Second, all assignments, whether explicit or via parameters passing in method calls, are checked for type compatibility. There are no automatic coercions or conversions of conflicting types as in some languages. The java compiler checks all expressions and parameters to ensure that the types are compatible.

* The Primitive Types
Java defines /eight primitive types of data/: *byte, short, int, long, char, float, double, and boolean.*
The primitive types are also commonly referred to as simple types, and both terms will be used in this book. These can be put in four groups:
- *Integers*: This group includes *byte, short, int, and long* which are for whole-valued signed numbers.
  
- *Floating-point numbers*: This group includes *float and double*, which represent numbers with fractional precision.

- *Characters*: This group includes *char*, which represents symbols in a character set, like letters and numbers.

- *Boolean*: This group includes boolean, which is a special type for representing true/false values.


You can use these types as-is, or to construct arrays or your own class types. Thus, they from the basis for all other types of data that you can create.


The primitive types represent single values--not complex objects. Although Java is otherwise completely object-oriented, the primitive types are not. They are analogous to the simple types found in most other non-object-oriented languages. The reason for this is efficiency. Making the primitive types into objects would have degraded performance too much.


Because of java's portability requirements, all data types have a /strictly defined range/. This allows programs to be written that are guaranteed to run without porting on any machine architecture. While strictly specifying the size of an integer may cause a small loss of performace in some environment, it is necessary in order to achieve portability.

** Integers
Java defines four integer types: *byte, short, int, and long*. All of these are signed, positive and negative values. Java does not support unsigned, positive-only integers.


The width of an integer type should not be thought of as the amount of storage it consumes, but rather as the behaviour it defines for variable and expressions of that type. The java run-time environment is free to use whatever size it wants, as long as the type behave as you declared them.


The width and ranges of these integer types vary widely, as shown in this table:
| Name  | Width | Range                                                   |
|-------+-------+---------------------------------------------------------|
| Long  |    64 | -9,223,372,036,854,775,808 to 9,223,372,036,854,775,808 |
| int   |    32 | -2,147,483,648 to 2,147,483,647                         |
| short |    16 | -32,768 to 32,767                                       |
| byte  |     8 | -128 to 127                                      |

*** byte
The smallest integer type is *byte*. This is a signed 8-bit type that has a range from -128 to 127. Variables of type *byte* are especially useful when you're working with a stream of data from a network or file. They are also useful when you're working with raw binary data that may not be directly compatible with java's other built-in type.


Byte variable are declared by use of the *byte* keyword. For example, the following declares two *byte* variables called *b and c*:
#+BEGIN_SRC java
byte b,c ;
#+END_SRC

*** Short
Short is a signed 16-bit type. It has a range from -32,768 to 32,767. It is probably the least-used java type. Here are some examples of *short* variable declarations:
#+BEGIN_SRC java
short s;
short t;
#+END_SRC

*** int
The most commonly used integer type is *int*. It is a signed 32-bit type that has range from -2,147,483,648 to 2,147,483,648.

*** long
*long* is a signed 64-bit type and is useful for those occasions where an *int* is not large enough to hold the desired value. The range of a *long* is quite large. This makes it useful when big, whole numbers are needed. For example, here is a program that computes the number of miles that light will travel in a specified number of days.
#+BEGIN_SRC java
class Light{
public static void main(String args[]){
int lightspeed;
long days;
long seconds;
long distance;

lightspeed = 186000;
days = 1000;
seconds = days * 24 * 60 * 60;
distance = lightspeed * seconds;

System.out.print("In " + days);
System.out.print(" days light will travel about ");
System.out.println(Distance + " miles.");
}
}
#+END_SRC
This program generates the following output:


In 1000 days light will travel about 16070400000000 miles.

** Floating-Point Types
Floating-point number, also known as real numbers, are used when evaluating expressions that require fractional precision. Java implements the standard (IEEE-754) set of floating-point types and operators. There are two kinds of floating-point types, *float* and *double*, which represent single- and double-precision numbers, respectively.


There width and ranges are shown here:
| Name   | Width in Bits | Approximate Range    |
|--------+---------------+----------------------|
| double |            64 | 4.9e-326 to 1.8e+308 |
| float  |            32 | 1.4e-045 to 3.4e+038 |

*** float
The type *float* specifies a single-precision value that uses 32 bits of storage. Single precision is faster on some processors and take half as much space as double precision, but will become imprecise when the values are either very large or very samll. Variables of type *float* are useful when you need a fractional component, but don't require a large degree of precision.
Examples are:
#+BEGIN_SRC java
float hightemp, lowtemp;
#+END_SRC

*** double
Double precision, as denoted by the *double* keyword, uses 64 bit to store a value. Double precision is actually faster than single precision on some modern processors that have been optomized for high-speed mathematical calculations. All transendental math functions, such as sin(), cos(), and sqrt(), return double values.

** Characters
In java, the data type used to store character is *char*. char is 8 bit wide. This is not the case in java. Instead, java uses unicode to represent characters. Unicode defines fully international characters set that can represent all of the characters found in all human languages. It is a unification of dozen of character sets, such as latin, Greek, Arabic, Cyrillic, Hebrew, Katakana, hangul, and many more. For this purpose, it requires 16 bits. Thus, *in java char is a 16-bit type.* The range of char is 0 to 65536. There are no negative chars.
